# Generated by Django 2.0.3 on 2018-10-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime',
            old_name='county',
            new_name='county_id',
        ),
    ]
