# Generated by Django 2.0.3 on 2018-10-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181018_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime',
            old_name='county_id',
            new_name='county',
        ),
    ]
